#!/usr/bin/env python3
"""Render the booth's runtime model prompts as a readable reference.

Every prompt the booth sends to Cortex is built in game/server.py from
game/config.json. That is the source of truth, but it is spread across a handler
and a config file, so this script gathers them into one document a person can
read - for transparency, and so another SE can port the activation to a new
event or language and see exactly what the model is asked at each beat.

It is generated, not hand-written: import server, fill each template against one
clearly-labelled EXAMPLE visitor, and write the result. Regenerate with
`python3 scripts/build_model_prompts.py` after changing config.json or the prompt
code. Runs offline - the corpus falls through to the committed context-bundle.json,
so no Snowflake connection is needed.

Two prompts (the workshop background fill and the QA relevance check) live inline
in server.py rather than in config; their templates are mirrored here with a
pointer to the function, the same way the decision tree mirrors the postbox lines.
"""
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "game"))

import server  # noqa: E402  (safe: the HTTP server is __main__-guarded)

cfg = server.load_config()
locs = cfg.get("locations") or {}

# One example visitor, used to fill every template so the rendered prompts read
# as a coherent single visit. Values are illustrative; braces in the raw
# templates are the real placeholders.
STATE = {
    "session_id": "example",
    "visitor": {
        "first_name": "Priya",
        "company": "an NHS Trust",
        "industry": "healthcare",
        "problem": "we retype referral letters into our system by hand all day",
        "company_country": "United Kingdom",
        "residency": "eu",
    },
    "held": ["Clinical notes & letters", "Referral & waiting list data"],
    "joined": ["PubMed Biomedical Research Corpus"],
    "platforms": ["Microsoft / Azure"],
    "poc": {
        "archetype": "extract-from-paperwork",
        "poc_name": "Referral reader",
        "summary": "Reads inbound referral letters and pulls the fields your "
                   "team retypes, so a clinician confirms rather than transcribes.",
        "features": ["AI_EXTRACT", "AI_PARSE_DOCUMENT", "Dynamic Tables"],
    },
}
WORKSHOP_INPUT = "a tool that reads our referral letters and extracts the fields we retype"
ASK_INPUT = "what would we need in place before we could trust the extracted fields?"

O = []
w = O.append


def block(prompt_text):
    w("```text")
    for line in prompt_text.split("\n"):
        w(line)
    w("```")
    w("")


def base():
    return "\n".join(server.base_context(cfg, STATE))


w("# The booth's model prompts")
w("")
w("_Generated by `scripts/build_model_prompts.py` from `game/config.json` and "
  "`game/server.py`. Every prompt the booth sends to Cortex is below, filled "
  "against one example visitor so it reads as a single visit. Regenerate after "
  "changing config or the prompt code._")
w("")
w("**The one rule that matters for porting:** the model only ever *picks and "
  "reflects*. The features, guides, listings and copy are ours - a closed set "
  "injected into the prompt as content - so the model chooses from them and "
  "speaks them back, but never invents a feature, a listing or a fact. The "
  "retrieval that builds the shortlist is deterministic (`game/context.py`), not "
  "a search service, so the same visitor input yields the same document.")
w("")
w("Model: COMPLETE prompts run on `%s`; the Workshop's first turn runs on the "
  "warm agent / `cortex exec`. Placeholders in braces are filled from the "
  "visitor's own answers at runtime; the italic values below are the example."
  % ((cfg.get("coco") or {}).get("complete_model", "mistral-large2")))
w("")
w("The example visitor: **Priya, an NHS Trust, healthcare** - problem \"we "
  "retype referral letters into our system by hand all day\"; holds clinical "
  "notes and referral data on Azure; joining PubMed; residency EU.")
w("")

# 1. Shared preamble
w("## 1. Shared preamble (`base_context`)")
w("")
w("Prepended to the Library, Marketplace and Workshop prompts. Sets who CoCo is "
  "and the speech-bubble constraints. From `base_context()` in `server.py`.")
w("")
block(base())

# 2. Library
w("## 2. The Library reflection (COMPLETE)")
w("")
w("Template: `config.locations.library.prompt`, prepended with the preamble. "
  "`{selection}` is what they ticked.")
w("")
lib = server.fill(locs.get("library", {}).get("prompt", ""), cfg, STATE,
                  selection=", ".join(STATE["held"]))
block(base() + "\n\n" + lib)

# 3. Marketplace
w("## 3. The Marketplace reflection (COMPLETE)")
w("")
w("Template: `config.locations.marketplace.prompt`, prepended with the preamble. "
  "`{selection}` is the listings they chose to join.")
w("")
mkt = server.fill(locs.get("marketplace", {}).get("prompt", ""), cfg, STATE,
                  selection=", ".join(STATE["joined"]))
block(base() + "\n\n" + mkt)

# 4. Workshop agentic
w("## 4. The Workshop, first turn (warm agent / `cortex exec`)")
w("")
w("The one agentic beat. Template: `config.locations.workshop.prompt`, prepended "
  "with the preamble. `{input}` is their one-line MVP description; `{feature_list}` "
  "is the entire closed feature list, injected so the model can only choose names "
  "that exist. Returns strict JSON (archetype, poc_name, features, reply).")
w("")
feature_list = ", ".join(sorted(server.load_features()))
wk = server.fill(locs.get("workshop", {}).get("prompt", ""), cfg, STATE,
                 input=WORKSHOP_INPUT, feature_list=feature_list)
block(base() + "\n\n" + wk)

# 5. Workshop background fill (mirrors refine_poc)
w("## 5. The Workshop background fill (COMPLETE)")
w("")
w("Runs silently after CoCo has spoken, while the visitor walks to the postbox. "
  "Fills the summary, first step, considerations and honest readiness score. "
  "Considerations are chosen by INDEX from a precomputed pool, so the prose is "
  "ours. Mirrors `refine_poc()` in `server.py`. `{candidates}` is the archetype's "
  "own pool from `archetypes.md`.")
w("")
_pool = server.archetype_defaults(cfg, STATE["poc"]["archetype"]).get("pool") or []
_listed = "\n".join("%d. %s" % (i + 1, c) for i, c in enumerate(_pool))
_vis = STATE["visitor"]
refine = (
    "You are helping shape a Snowflake proof of concept. Be concrete and never "
    "generic.\n\n"
    "Person: %s at %s, %s.\n"
    "They hold: %s.\n"
    "They will attach: %s.\n"
    "They asked the POC to: \"%s\"\n"
    "It is a '%s' build called '%s'.\n\n"
    "Candidate considerations:\n%s\n\n"
    "Return ONLY minified JSON, no prose, no code fence, with exactly these keys: "
    "{\"summary\": 2 sentences on what it does and why it matters to THEM, "
    "\"first_step\": one concrete first action, \"considerations\": array of "
    "exactly 3 integers, the numbers of the most relevant candidates above, "
    "\"readiness\": integer 1-5}\n"
    "Score readiness strictly: only award 4 or 5 if they named specific data, a "
    "specific question and a specific user. Nobody sees the number, so be honest "
    "rather than kind."
    % (_vis["first_name"], _vis["company"],
       server.industry_name(cfg, _vis["industry"]),
       ", ".join(STATE["held"]), ", ".join(STATE["joined"]),
       WORKSHOP_INPUT, STATE["poc"]["archetype"], STATE["poc"]["poc_name"],
       _listed))
block(refine)

# 6. Ask CoCo (optional visitor question)
w("## 6. \"Ask CoCo one thing\" (optional, `cortex exec` with tools)")
w("")
w("Only if the visitor types a question at the Workshop. Template: "
  "`config.ask.prompt`, prepended with the preamble. This is the one place a "
  "docs-lookup tool is budgeted for.")
w("")
ask = server.fill((cfg.get("ask") or {}).get("prompt", ""), cfg, STATE,
                  input=ASK_INPUT, poc_name=STATE["poc"]["poc_name"],
                  poc_summary=STATE["poc"]["summary"])
block(base() + "\n\n" + ask)

# 7. QA relevance (mirrors _qa_relevance)
w("## 7. The QA relevance check (COMPLETE, fails open)")
w("")
w("Runs at send, before the document is staged. Judges only whether the finished "
  "POC addresses the stated problem; a false verdict is a flag for review, not a "
  "block. Mirrors `_qa_relevance()` in `server.py`.")
w("")
_poc = STATE["poc"]
qa = (
    "You are a strict reviewer. A booth built this proof-of-concept plan for a "
    "visitor. Judge ONLY whether it addresses the problem they stated.\n\n"
    "Their problem: \"%s\"\n\n"
    "The POC: name=\"%s\"; builds=\"%s\"; features=%s\n\n"
    "Reply with ONLY minified JSON, nothing else: "
    "{\"relevant\": true or false, \"issue\": \"at most 12 words, empty if relevant\"}"
    % (_vis["problem"], _poc["poc_name"], _poc["summary"],
       ", ".join(_poc["features"])))
block(qa)

out_path = os.path.join(ROOT, "skills", "loco4coco", "references",
                        "model-prompts.md")
io.open(out_path, "w", encoding="utf-8").write("\n".join(O) + "\n")
print("wrote %s  (%d lines)" % (out_path, len(O)))
